language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4.2.4'
install:
    npm install -g npm@'>=3.3.12'
before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
before_script:
  - npm prune
after_success:
  - npm run release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
