language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7.2.1'
install:
  - npm install -g npm@'>=3.3.12'
before_script:
  - npm prune
after_success:
  - npm run release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
